# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GpsLat', models.FloatField()),
                ('GpsLng', models.FloatField()),
                ('GpsPositionRawData', models.CharField(max_length=50)),
                ('Owner', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('CreatedOn', models.DateField()),
                ('ModifiedOn', models.DateField()),
                ('StartOfEvent', models.DateField()),
                ('EndOfEvent', models.DateField()),
                ('Adress', models.CharField(max_length=50)),
                ('AdressComplement', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Picture', models.ImageField(upload_to=b'')),
                ('ChurchLink', models.CharField(max_length=50)),
                ('YoutubeLink', models.CharField(max_length=50)),
                ('KeyWord', models.CharField(max_length=50)),
            ],
        ),
    ]
